<a href="https://colab.research.google.com/github/charmin16/charmin16/blob/main/Copy_of_homoye_lesson_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = [6,7,8,9]
print(type(arr))

a = np.array(arr)
print(type(a))

print(a.shape)

print(a.dtype)



<class 'list'>
<class 'numpy.ndarray'>
(4,)
int64


In [ ]:
Get the dimension of 'a' on the cell above by using ndim

In [ ]:
print(a.ndim)
b = np.array([[1,2,3,21], [5,6,7,18], [8, 9, 1, 12]])
print(b)
print(b.shape)
print(b.ndim)

1
[[ 1  2  3 21]
 [ 5  6  7 18]
 [ 8  9  1 12]]
(3, 4)
2


In [ ]:
import numpy as np
arr = [3,4,5,6,7]
arn = np.array(arr)
# print(type(arr))
# print(type(arn))
# print(arn.shape)
# print(arn.dtype)

# a = np.array([[9,2,3,4,5], [12,4,5,6,9], [ 22,8,9,4,1]])
# print(a)
# print(type(a))
# print(a.shape)
# print(a.ndim)
# print(a.dtype)
# print(arn.shape)
# print(arn.ndim)

# a 2x3 array with random values
# np.random.random((2,3))

# a 2x3 array of zeros
# np.zeros((2,3))

# a 2x3 array of ones
# np.ones((2,3))

# a 3x3 identity matix
# np.identity(3)

a = [4,8,9,12]
az = np.array(a)

b = np.array([[1, 2, 3], [4, 5, 6]])

c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])

d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])

e = c + d

print(b[1,1]) # What this means: the first 1 in the bracket represents the second second dimension: [4,5,6], the seond 1 represents the index(second in this second dimension). So b[1,1] = 5
f = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18], [19, 20, 21]])
# print(f[:3, :2]) # :3 means we are considering 0,1,2 dimensions which is the first three arrays. We will now perform :2 on these first three arrays of interest, therefor the 0 and 1 index in the first three arrays will suffice
# print(f[:2, :2])

# Other advanced methods of indexing are shown below
# print(f[[2, 0, 3, 1], [2, 1, 0, 2]]) # from the 2nd dimension(third  array) pick the second index(3rd element). From the 0th dimension(first array), pick the first index(second element), just like that till you get to the end

print(f[f>15]). # boolean indexing meeting a specified condition

# ls = [1,2,3,4,5,6]
# print(ls[0:3])

# print(az[0])
# print(b[0,0])
# print(b[1,2])
# print(c[0,1])


# print(e)
# print(c.dtype)
# print(c + d)
# print(c * d)
# print(5/d)
# print(c ** 2)

5
[16 17 18 19 20 21]


In [ ]:
import pandas as pd

days = pd.Series(['Monday', 'Tuesday', 'Wednesday'])
# print(days)

# creating series with a numpy array

days_list = np.array(['Monday', 'Tuesday', 'Wednesday'])
numpy_days = pd.Series(days_list)
#print(numpy_days)

# Using strings as index

days = pd.Series(['Monday', 'Tuesday', 'Wednesday'],
index = ['a', 'b', 'c'])

# Create series from a dictionary

days1 = pd.Series({'a': 'Monday', 'b': 'Tuesday', 'c': 'Wednesday'})
print(days)
print(days1)

a       Monday
b      Tuesday
c    Wednesday
dtype: object
a       Monday
b      Tuesday
c    Wednesday
dtype: object


In [ ]:
import numpy as np
# a = np.array([1,2,3,4,5,6])
# print(type(a))
# print(a.dtype)
# print(a.shape)
# print(a.ndim)

b = np.array([[1,2,3,4], [6,7,8,11], [1,7,9,10], [1,3,5,14]])
# print(type(b))
# print(b.shape)
# print(b.dtype)
# print(b.ndim)

# print(b[0,2])
# print(b[1,0])
# print(b[2,2])

# print(b[:3, :3])
# print(b[0, :3])
# print(b[1, :-1])

c = np.array(['manager', 'orange', 'guava'])
# print(type(c))
# print(c.dtype)




<class 'numpy.ndarray'>
<U7


In [ ]:
import numpy as np
import pandas as pd

days = pd.Series(['Monday', 'Tuesday', 'Wednesday'])
# print(days)

# Creating series with a numpy array
days_list = np.array(['Monday', 'Tuesday', 'Wednesday'])
numpy_days = pd.Series(days_list)
# print(numpy_days)

# Using strings as index

dayi = pd.Series(['Monday', 'Tuesday', 'Wednesday'], 
                 index = ['a', 'b', 'c'])
#print(dayi)

# Create series from a dictionary

dayd = pd.Series({'a': 'Monday', 'b': 'Tuesday', 'c': 'Wednesday',
                  'e': 'Thursday'})
# print(dayd)

# Series can be accessed using the specified index as shown below

# print(days[0])
# print(days[1:])
# print(dayi[1:])
# print(dayd[0:3:2]). # from index 0(first element) to index 3 at an interval of 2
# print(dayd[::-1]) # Reverses the order/arrangement
# print(dayi['c'])
# z = [1,2,3,4,5,6]
# print(z[::-1])

# A DataFrame can be be described as a table (2 dimensions) made up of many series with the same index
# It holds data in rows and columns just like a spreadsheet. Series, dictionaries, lists and other dataframes
# and numpy arrays can be used to create new ones

# print(pd.DataFrame())

# Create a dataframe from a dictionary

df_dict = {'Country': ['Ghana', 'Kenya', 'Nigeria', 'Togo'],
           'Capital': ['Accra', 'Nairobi', 'Abuja', 'Lome'],
           'Population': [10000, 8500, 35000, 12000],
           'Age': [60, 70, 80, 75] }
dfd = pd.DataFrame(df_dict, index = [2,4,6,8])
# print(dfd)

df_list = [['Ghana', 'Accra', 10000, 60],
           ['Kenya', 'Nairobi', 8500, 70],
           ['Nigeria', 'Abuja', 35000, 80],
           ['Togo', 'Lome', 12000, 75]]
dfl = pd.DataFrame(df_list, columns = ['Country', 'Capital', 'Population', 'Age'],
                   index = [1,2,3,4])
# print(dfl)

# at, iat, iloc and loc are accessors used to retrieve data in dataframes. iloc selects
# from the rows and columns by using integer index to locate positions while loc selects
# rows and columns using labels. at and iat are used to retrieve single values such that at
# uses the column and row labels and iat uses indices.

# select the row in the at index 3
# print(dfd.iloc[0]) # index 0 would be the first item(row) on the table

# select row with index number
# print(dfd.loc[4])
# print(dfd.loc[8])

# select the capital column
# print(dfd['Capital'])

# Using at and iat

# print(dfd.at[6, 'Country'])
# print(dfd.at[8, 'Capital'])
# print(dfd.iat[0,1])
# print(dfd.iat[1,2])

'''Indexing in pandas are immutable arrays with unique elements or can be 
described as ordered sets for retrieving data in a dataframe and collaborating
with multiple dataframes.

The important Pandas functionalities: indexing, reindexing, selection, group,
drop entities, ranking, sorting, duplicates and indexing by hierachy.'''

# print(dfd['Population'].sum())
# print(dfd['Age'].sum())
# print(dfd.mean())
# print(dfd.describe())

# THE MISSING DATA ENIGMA
'''Often data used for analysis in real life scenarios is imcomplete as a result of
omission, faulty devices and mnay other factors. Pandas represent missing values as
NA or NaN which  can be filled, removed and detected with functions like fillna(),
dropna(), isnull(), replace()'''

new_dic2 = {'Name': ['James', 'Yemen', 'Caro', np.nan],
          'Porfession': ['Researcher', 'Artist', 'Doctor', 'Writer'],
          'Height': [np.nan, 175,180, 150],
          'Experience': [12, np.nan, 10, 8]}
new_df = pd.DataFrame(new_dic2)
# print(new_df)

# Check for cells with missing values as True
# #print(new_df.isnull())

# remove rows with  missing  values
print(new_df.dropna())

   Name Porfession  Height  Experience
2  Caro     Doctor   180.0        10.0


In [ ]:
import numpy as np
import pandas as pd
days_week = pd.Series(['Monday', 'Tuesday', 'Wedesday', 'Thursday'],
index = [1, 2, 3, 4])
days = pd.Series(days_week)
# print(type(days))
# print(days_week)

dayz = pd.Series(['Mon', 'Tues', 'Wed', 'Thurs', 'Fri'], 
                 index = ['a', 'b', 'c', 'd', 'e'])
# print(dayz)
# print(dayz['b':])
# print(dayz[2])

df = {'Country': ['Nigeria', 'Ghana', 'Kenya', 'Togo'],
       'Capital': ['Abuja', 'Accra', 'Nairobi', 'Lome'],
       'Population': [100000, 80000, 60000, 40000],
       'Age': [88, 74, 79, 67]}
dfd1 = pd.DataFrame(df)
dfd = pd.DataFrame(df, index = ['a', 'b', 'c', 'd'])
#print(dfd1)
# print(dfd)

df = [['Nigeria', 'Abuja', 100000, 88], ['Ghana', 'Accra', 80000, 74],
      ['Kenya', 'Nairobi', 60000, 79], ['Togo', 'Lome', 40000, 67]]
dfl = pd.DataFrame(df, columns = ['Country', 'Capital', 'Population', 'Age'])
dfli = pd.DataFrame(df, columns = ['Country', 'Capital', 'Population', 'Age'],
                   index = ['a', 'b', 'c', 'd'])
# print(dfli)

# '''at iat, iloc, loc are accessors used to retrieve data in dataframes.
# iloc selects values from the rows and columns by using integer index to
# locate positions while loc selects rows or columns using labels. This is
# demonstrated below'''

# select the row in the at index 2
# print(dfl.iloc[2:])

# select the row with index label 'b' in dfd
# print(dfd.loc['a'])
# print(dfli.loc['b':])
# print(dfd['Capital'])

# at and iat are used to retrieve single values such that at
# uses the column and row labels and iat uses indices

# print(dfd.iat[3,3])
# print(dfli.iat[1,2])
# print(dfli.at['d', 'Capital'])
# print(dfli.at['c', 'Age'])

# print(dfd['Population'].sum())
# print(dfd.mean())
# print(dfd.describe())
    
# DATA TYPES AND DATA WRANGLING

csv_df = pd.read_csv('sample_file.csv')
csv_df.to_csv('sample_file.csv', index = False)
# print(csv_df)

# sometimes dependent on the xlrd library which can be installed by running
# pip install xlrd in the terminal

excel_df = pd.read_excel('sample_file.xlsx')
excel_df.to_excel('sample_file.xlsx')

# read table from a webpage and save as a dataframe

html_df = pd.read_html('http://www.webpage.com/sampledata.html')
html_df.to_html('sample_file.html')

# Pandas can connect to databases, get data with queries and save in a dataframe

url = 'https://github.com/WalePhenomenon/climate_change/blob/master/fuel_ferc1.csv?raw = true'
fuel_data = pd.read_csv(ur1,error_bad_lines = False)
fuel_data.describe(include = 'all')
print(fuel_data)

FileNotFoundError: ignored